<?php

namespace Ascii\Art\AnalyzerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Ascii\Art\AnalyzerBundle\Entity\Char;

/**
 * CharsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharsRepository extends EntityRepository
{
	/**
	 * @param bool $inverted
	 * @return array
	 */
	public function getAllChars($inverted = false)
	{
		$chars = $this->findAll();

		$datas = [];

		/**
		 * @var Char $char
		 */
		foreach ($chars as $char) {
			$index = $inverted ? 255 - $char->getLuminosity() : $char->getLuminosity();
			$datas[$index] = $char->getAsciiChar();
		}

		return $datas;
	}
}
