<?php

namespace Ascii\Art\AnalyzerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Ascii\Art\AnalyzerBundle\Entity\Char;

/**
 * CharsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharsRepository extends EntityRepository
{
	/**
	 * @return array
	 */
	public function getAllChars()
	{
		$chars = $this->findAll();

		$datas = [];
		/**
		 * @var Char $char
		 */
		foreach ($chars as $char) {
			$datas[$char->getLuminosity()] = $char->getAsciiChar();
		}

		return $datas;
	}
}
